version: '3.8'

services:

  # DATABASE MAGIC (primary)
  primary-pg-0:
    container_name: foxtrot-primary-pg-0
    image: bitnami/postgresql-repmgr:14
    restart: always
    ports:
      - 5432
    volumes:
      - ./primary-db/pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=examplesys
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=primary-pg-0
      - REPMGR_PARTNER_NODES=primary-pg-0,primary-pg-1
      - REPMGR_NODE_NAME=primary-pg-0
      - REPMGR_NODE_NETWORK_NAME=primary-pg-0
  primary-pg-1:
    container_name: foxtrot-primary-pg-1
    image: bitnami/postgresql-repmgr:14
    restart: always
    ports:
      - 5432
    volumes:
      - ./primary-db/pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=examplesys
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=primary-pg-0
      - REPMGR_PARTNER_NODES=primary-pg-0,primary-pg-1
      - REPMGR_NODE_NAME=primary-pg-1
      - REPMGR_NODE_NETWORK_NAME=primary-pg-1
  primary-pgpool:
    container_name: foxtrot-primary-pgpool
    image: bitnami/pgpool:4
    restart: always
    ports:
      - 5432:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:primary-pg-0:5432,1:primary-pg-1:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  # DATABASE MAGIC (secondary)
  secondary-pg-0:
    container_name: foxtrot-secondary-pg-0
    image: bitnami/postgresql-repmgr:14
    restart: always
    ports:
      - 5432
    volumes:
      - ./secondary-db/pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=dw
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=secondary-pg-0
      - REPMGR_PARTNER_NODES=secondary-pg-0,secondary-pg-1
      - REPMGR_NODE_NAME=secondary-pg-0
      - REPMGR_NODE_NETWORK_NAME=secondary-pg-0
  secondary-pg-1:
    container_name: foxtrot-secondary-pg-1
    image: bitnami/postgresql-repmgr:14
    restart: always
    ports:
      - 5432
    volumes:
      - ./secondary-db/pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_POSTGRES_PASSWORD=postgres
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=dw
      - REPMGR_PASSWORD=postgres
      - REPMGR_PRIMARY_HOST=secondary-pg-0
      - REPMGR_PARTNER_NODES=secondary-pg-0,secondary-pg-1
      - REPMGR_NODE_NAME=secondary-pg-1
      - REPMGR_NODE_NETWORK_NAME=secondary-pg-1
  secondary-pgpool:
    container_name: foxtrot-secondary-pgpool
    image: bitnami/pgpool:4
    restart: always
    ports:
      - 5433:5432
    environment:
      - PGPOOL_BACKEND_NODES=0:secondary-pg-0:5432,1:secondary-pg-1:5432
      - PGPOOL_SR_CHECK_USER=postgres
      - PGPOOL_SR_CHECK_PASSWORD=postgres
      - PGPOOL_ENABLE_LDAP=no
      - PGPOOL_POSTGRES_USERNAME=postgres
      - PGPOOL_POSTGRES_PASSWORD=postgres
      - PGPOOL_ADMIN_USERNAME=postgres
      - PGPOOL_ADMIN_PASSWORD=postgres
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/pgpool/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  # BACKEND SERVICES
  backend-1:
    container_name: foxtrot-backend-1
    image: openjdk:11
    restart: always
    command: sh -c "
      sleep 60 &&
      cd /usr/local &&
      ls -la &&
      java -jar sys-foxtrot-rest-0.0.1.jar"
    ports:
      - '8000:8080'
    environment:
      DB_HOST: primary-pgpool
    volumes:
      - ../sys-foxtrot-rest/build/libs/sys-foxtrot-rest-0.0.1.jar:/usr/local/sys-foxtrot-rest-0.0.1.jar
    depends_on:
      - primary-pg-0
      - primary-pg-1
      - primary-pgpool

  backend-2:
    container_name: foxtrot-backend-2
    image: openjdk:11
    restart: always
    command: sh -c "
      sleep 60 &&
      cd /usr/local &&
      ls -la &&
      java -jar sys-foxtrot-rest-0.0.1.jar"
    ports:
      - '9000:8080'
    environment:
      DB_HOST: primary-pgpool
    volumes:
      - ../sys-foxtrot-rest/build/libs/sys-foxtrot-rest-0.0.1.jar:/usr/local/sys-foxtrot-rest-0.0.1.jar
    depends_on:
      - primary-pg-0
      - primary-pg-1
      - primary-pgpool

  nginx-backend-lb:
    container_name: foxtrot-backend-lb
    image: nginx:1.13
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - primary-pg-0
      - primary-pg-1
      - primary-pgpool
      - backend-1
      - backend-2

  frontend-1:
    container_name: foxtrot-frontend-1
    image: nginx:1.13
    ports:
      - "3000:80"
    volumes:
      - ./config/nginx/nginx-ui.conf:/etc/nginx/nginx.conf
      - ../sys-foxtrot-ui/build:/usr/share/nginx/html/

  frontend-2:
    container_name: foxtrot-frontend-2
    image: nginx:1.13
    ports:
      - "4000:80"
    volumes:
      - ./config/nginx/nginx-ui.conf:/etc/nginx/nginx.conf
      - ../sys-foxtrot-ui/build:/usr/share/nginx/html/

  nginx-frontend-lb:
    container_name: foxtrot-frontend-lb
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx-lb-ui.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend-1
      - frontend-2

  # ETL SERVICES
  etl-1:
    container_name: foxtrot-etl-1
    image: openjdk:11
    restart: always
    command: sh -c "
      sleep 70 &&
      cd /usr/local &&
      ls -la &&
      java -jar sys-foxtrot-etl-0.0.1.jar"
    ports:
      - '8081:8080'
    environment:
      DB_HOST: primary-pgpool
      DB_DW_HOST: secondary-pgpool
      DB_DW_HOST_PORT: 5432
    volumes:
      - ../sys-foxtrot-etl/build/libs/sys-foxtrot-etl-0.0.1.jar:/usr/local/sys-foxtrot-etl-0.0.1.jar
    depends_on:
      - secondary-pg-0
      - secondary-pg-1
      - secondary-pgpool
